# Generated by Django 5.1.7 on 2025-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('tekst', models.TextField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, default=False, null=True)),
                ('afbeelding', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
