# Generated by Django 5.1.7 on 2025-04-09 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sbwe', '0003_aanvraag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('start', models.TimeField(blank=True, null=True)),
                ('eind', models.TimeField(blank=True, null=True)),
                ('website', models.URLField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aanvraag',
            name='akkoord',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aanvraag',
            name='Nawnodig',
            field=models.BooleanField(default=False),
        ),
    ]
