# Generated by Django 5.1.7 on 2025-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sbwe', '0005_inschrijf_delen_inschrijf_telefoon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inschrijf',
            name='voorzieing',
        ),
        migrations.AddField(
            model_name='inschrijf',
            name='akkoord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inschrijf',
            name='voorziening',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inschrijf',
            name='werk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
