# Generated by Django 5.1.7 on 2025-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sbwe', '0006_remove_inschrijf_voorzieing_inschrijf_akkoord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanvraag',
            name='bedrijfsnaam',
            field=models.CharField(max_length=200, verbose_name='Bedrijfsnaam'),
        ),
        migrations.AlterField(
            model_name='aanvraag',
            name='naam',
            field=models.CharField(max_length=200, verbose_name='Voor & achternaam'),
        ),
    ]
