# Generated by Django 5.1.7 on 2025-04-13 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sbwe', '0007_alter_aanvraag_bedrijfsnaam_alter_aanvraag_naam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnaam', models.CharField(default='geen', max_length=200, verbose_name='Bedrijfsnaam')),
                ('naam', models.CharField(max_length=200, verbose_name='Voor & achternaam')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('datum', models.DateField(default=django.utils.timezone.now, null=True)),
                ('starttijd', models.TimeField(null=True)),
                ('eindtijd', models.TimeField(null=True)),
                ('akkoord', models.BooleanField(default=False)),
                ('Nawnodig', models.BooleanField(default=False)),
                ('gasten', models.CharField(choices=[('1 tot 20 personen', '1-20'), ('20 tot 40 personen', '20-40'), ('40 tot 80 personen', '40-80')], default='Onbekend', max_length=30, null=True)),
                ('activiteit', models.CharField(choices=[('Concert', 'Concert'), ('Opname', 'Opname'), ('Les', 'Les'), ('Anders', 'Anders, geef toelichting')], default='Onbekend', max_length=40, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Inschrijf',
            new_name='Wacht',
        ),
        migrations.DeleteModel(
            name='Aanvraag',
        ),
    ]
