# Generated by Django 5.1.7 on 2025-05-15 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sbwe', '0008_reserve_rename_inschrijf_wacht_delete_aanvraag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factuur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijfsnaam', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bedrijfsnaam')),
                ('naam', models.CharField(max_length=200, null=True, verbose_name='Voor & achternaam')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('adres', models.CharField(max_length=80, null=True, verbose_name='Adres')),
                ('postcode', models.CharField(max_length=20, null=True, verbose_name='Postcode')),
            ],
        ),
        migrations.AddField(
            model_name='wacht',
            name='startdatum',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='bedrijfsnaam',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bedrijfsnaam'),
        ),
    ]
