# Generated by Django 5.1.7 on 2025-05-20 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sbwe', '0009_factuur_wacht_startdatum_alter_reserve_bedrijfsnaam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='eindtijd',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='starttijd',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
