# Generated by Django 5.1.7 on 2025-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sbwe', '0010_alter_reserve_datum_alter_reserve_eindtijd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wacht',
            old_name='vierkantem',
            new_name='vierkantm',
        ),
        migrations.AlterField(
            model_name='wacht',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
    ]
